name: irony # This will become the name of your environment
dependencies: # The list of packages to include in your environment
    - python=3.12 # You can specify versions
    - jupyterlab
    - pytorch
    - transformers[torch]
    - pip # Install pip in your environment
